[Interface]
PrivateKey = eJdprswdc/RenCUVseoIHjMCHXYpucYx6394ZLdaM14=
Address = 10.9.3.1/24
ListenPort = 49151

# NAT rule Execution when VPN is started
PostUp = iptables -t nat -A POSTROUTING -s 10.9.3.0/24 -o enp0s3 -j MASQUERADE

# NAT rule execution when VPN is stopped
PostDown = iptables -t nat -D POSTROUTING -s 10.9.3.0/24 -o enp0s3 -j MASQUERADE

# 1st Client : PC-nomad
[Peer]
PublicKey = PGls9AinXfS5IdeNqjo13gQI40lYISgFKdSFN/d7yFM=
AllowedIPs = 10.9.3.100/32, <private-LAN-pc-nomade>

# 2nd Client : Phone
[Peer]
PublicKey = nThYuugUcSPpoTjlmwK9LLNXYA9iMl0r0ox8nmUx/Ak=
AllowedIPs = 10.9.3.200/32
