[Interface]
Address = 10.9.3.100/24
PrivateKey = QK7A/v0MbonV4EDDezE9+e4itF9Q5tM7/j5e+lNmklM=

# Connexion au serveur VPN Paris-Montrouge
[Peer]
PublicKey = k8KX5hzEe6J6UlkjyJiVUfQwJaNPd+lHSsJDnKrhDFI=
Endpoint = 82.X.Y.Z:49151
AllowedIPs = 10.9.2.0/24, 10.9.3.0/24, 172.20.10.0/28, 192.168.1.0/24, 192.168.100.0/24
PersistentKeepalive = 25
