[Interface]
PrivateKey = eJdprswdc/RenCUVseoIHjMCHXYpucYx6394ZLdaM14=
Address = 10.9.3.1/24
ListenPort = 49151

# On exécute les commandes d'ajout des règles lorsque le VPN démarre
PostUp = iptables -A FORWARD -i %i -j ACCEPT ; iptables -A FORWARD -o %i -j ACCEPT ; iptables -t nat -A POSTROUTING -s 10.9.3.0/24 -o enp0s3 -j MASQUERADE

# Et on rajoute des commandes pour les supprimer lorsque le VPN est éteint
PostDown = iptables -D FORWARD -i %i -j ACCEPT ; iptables -D FORWARD -o %i -j ACCEPT ; iptables -t nat -D POSTROUTING -s 10.9.3.0/24 -o enp0s3 -j MASQUERADE

# 1er Client : PC-nomade
[Peer]
PublicKey = PGls9AinXfS5IdeNqjo13gQI40lYISgFKdSFN/d7yFM=
AllowedIPs = 10.9.3.100/32

# 2nd Client : Iphone
[Peer]
PublicKey = nThYuugUcSPpoTjlmwK9LLNXYA9iMl0r0ox8nmUx/Ak=
AllowedIPs = 10.9.3.200/32
