################
# CONFIGURATION CLIENT OPENVPN  
# CLIENT NY --> PARIS-MONROUGE
################ 

client
dev tun
proto udp

port 9999

# Serveur VPN principal (Paris-Montrouge)
remote 82.X.Y.Z 1194

# Logging
verb 3
log vpn-client-NY.log

################
# SECURITE 
################ 

# TLS / certificats
tls-client
ca /etc/openvpn/tls/cacert.pem
cert /etc/openvpn/tls/client-NY.crt
key /etc/openvpn/tls/client-NY.key

# Chiffrements autorisés pour le handshake TLS
data-ciphers AES-256-GCM:AES-128-GCM
cipher AES-256-GCM

################
# STATEGIE 
# DE RECONNEXION 
#################

# ne jamais abandonner la recherche du serveur
resolv-retry infinite 	

# pas besoin de se lier à un port local
nobind

# Detection rapide de la panne
keepalive 5 30

