################
# CONFIGURATION CLIENT OPENVPN  
# CLIENT TOKYO --> PARIS-MONROUGE
################ 

client
dev tun
proto udp

port 9998

# Serveur VPN principal (Paris-Montrouge)
remote 82.X.Y.Z 1194

# Logging
verb 3
log vpn-client-tokyo.log

################
# SECURITE 
################ 
# TLS / certificats
tls-client
ca /etc/openvpn/tls/cacert.pem
cert /etc/openvpn/tls/client-tokyo.crt
key /etc/openvpn/tls/client-tokyo.key
auth SHA512

# Chiffrements autorisés pour le handshake TLS
data-ciphers AES-256-GCM:AES-128-GCM
cipher AES-256-GCM

################
# STATEGIE 
# DE RECONNEXION 
#################

# Ne jamais abandonner la recherche du serveur
resolv-retry infinite 	

# Evite de se lier à un port local
nobind

# Detection rapide de la panne
keepalive 5 30


