################################
# TOKYO CLIENT OPENVPN  CONFIGURATION
################################

client
dev tun
proto udp

# Connection to Primary VPN server (Paris-Montrouge)
remote 82.X.Y.Z 1194
# Connection to Backup VPN server (Paris-Montrouge)
remote 82.X.Y.Z 1195

# Logging
verb 3
log vpn-client-tokyo.log

################
# SECURITY
################ 

# TLS / certificates
tls-client
ca /etc/openvpn/tls/cacert.pem
cert /etc/openvpn/tls/client-tokyo.crt
key /etc/openvpn/tls/client-tokyo.key
auth SHA512

# Permitted ciphers for the TLS handshake
data-ciphers AES-256-GCM:AES-128-GCM
cipher AES-256-GCM

################
# RECONNECTION 
# STRATEGY 
#################

# Never give up on finding the server
resolv-retry infinite 	

# Avoid binding to a local port
nobind

# Maitain the connection for a rapid fault detection: ping every 5s the server & restart the connexion if no response for 30s 
ping 5
ping-restart 30

# Wait 5s max to connect
# 1 max attempt/server
connect-timeout 5
connect-retry 1
