#########################################
## BACKUP OPENVPN SERVER CONFIGURATION
## SERVER AUBERVILLIERS --> TOKYO/NY
#########################################

dev tun
port 1195
proto udp

# Backup VPN network
server 10.9.2.0 255.255.255.0

# Avoid using the net30 topology (which is now obsolete)
topology subnet

# Communication inter-clients VPN
client-to-client

# Enabled to read the iroute for Tokyo & NY
client-config-dir /etc/openvpn/ccd

# Logging
verb 3
log vpn-srv-auber.log

# Keep the connection open
ping 5
ping-restart 30

#################
## SECURITY
#################

# TLS / certificats
tls-server
ca /etc/openvpn/tls/cacert.pem
cert /etc/openvpn/tls/server-auber.crt
key /etc/openvpn/tls/server-auber.key
dh /etc/openvpn/tls/dh2048.pem

# chiffrements autorisés pour la négociation 
data-ciphers AES-256-GCM:AES-128-GCM 

#  chiffrement par défaut (pour la compatibilité) 
cipher AES-256-GCM 

###################
## ROUTING (OPENVPN) 
###################

# Local primary route injected to the VPN clients’ LAN 
route 172.20.10.0 255.255.255.240 
			
# Routes injected to VPN clients, that go through the VPN tunnel
push "route 192.168.1.0 255.255.255.0"
push "route 192.168.100.0 255.255.255.0"

#####################
## ROUTING (WIREGUARD)
#####################

# Routes injected to VPN clients, that go through the VPN tunnel
push "route 10.9.3.0 255.255.255.0"

# Routes injected to VPN clients, that go through the VPN tunnel
# route 10.9.3.0 255.255.255.0 192.168.100.200 5

