#########################################
## CONFIGURATION SERVEUR OPENVPN
## SERVEUR PARIS-MONTROUGE --> TOKYO/NY
#########################################

dev tun
port 1194
proto udp

# Réseau VPN
server 10.9.1.0 255.255.255.0

# Evite l'utilisation de la topologie net30 (devenue obsolète)
topology subnet

# Communication inter-clients VPN
client-to-client

# Logging
verb 3
log vpn-srv-parimont.log

# CDD activé pour lire le iroute de Tokyo & NY
client-config-dir /etc/openvpn/ccd

# Maintien de la connexion
keepalive 5 30

push "dhcp-option DNS 8.8.8.8"

#################
## SECURITE
#################

# TLS / certificats 
tls-server
ca /etc/openvpn/tls/cacert.pem
cert /etc/openvpn/tls/server-parismont.crt
key /etc/openvpn/tls/server-parismont.key
dh /etc/openvpn/tls/dh2048.pem
auth SHA512

 # Chiffrements autorisés pour la négociation 
data-ciphers AES-256-GCM:AES-128-GCM 

# Chiffrement par défaut (pour la compatibilité) 
cipher AES-256-GCM 

#################
# ROUTES 
#################

# Route principale vers le réseau LAN des clients VPN (Métrique basse = priorité haute)
route 172.20.10.0 255.255.255.240 vpn_gateway 10

# Route de secours vers le réseau LAN des clients VPN
route 172.20.10.0 255.255.255.240 192.168.100.210 100

# Route vers le tunnel VPN de secours
route 10.9.2.0 255.255.255.0 192.168.100.210

# Routes ajoutées aux clients VPN, qui passent via le tunnel IP principal
push "route 192.168.1.0 255.255.255.0"
push "route 192.168.100.0 255.255.255.0"
