#########################################
## OPENVPN SERVER CONFIGURATION
## SERVER PARIS-MONTROUGE --> TOKYO/NY
#########################################

dev tun
port 1194
proto udp

# VPN Network
server 10.9.1.0 255.255.255.0

# Avoid using the net30 topology (which is now obsolete)
topology subnet

# Communication inter-clients VPN
client-to-client

# Logging
verb 3
log vpn-srv-parimont.log

# Enabled to read the iroute for Tokyo & NY
client-config-dir /etc/openvpn/ccd

# Keep the connection open
ping 5
ping-restart 30

#################
## SECURITY  
#################

# TLS / certificats 
tls-server
ca /etc/openvpn/tls/cacert.pem
cert /etc/openvpn/tls/server-parismont.crt
key /etc/openvpn/tls/server-parismont.key
dh /etc/openvpn/tls/dh2048.pem
auth SHA512

 # Permitted ciphers for trading 
data-ciphers AES-256-GCM:AES-128-GCM 

# Default encryption (for compatibility) 
cipher AES-256-GCM 

#################
# ROUTING CONFIGURATION
#################

# Primary route to the VPN clients’ LAN 
route 172.20.10.0 255.255.255.240

# Routes injected to VPN clients, which go through the primary VPN tunnel
push "route 192.168.1.0 255.255.255.0"
push "route 192.168.100.0 255.255.255.0"
