#!/bin/bash

## Location : /usr/local/bin/
# Comment faire pour activez la connexion vers le serveur vpn wireguard du site Aubervillier quand la connexion VPN vers le site montrouge est coupé ??? (Bonus)

# Reachability test of the Primary VPN (Paris) 
ping -c 1 -W 1 10.9.3.1 > /dev/null

# VPN principal UP: stop the backup vpn (if active)
if [ $? -eq 0 ]; then					# $?=0 : vpn server auber up, $?=1 : vpn server auber down
 	netstat -lu | grep 49150 > /dev/null
 	if [ $? -eq 0 ]; then
		wg-quick down wg0-auber
	fi
# VPN Primary DOWN → launch the Backup VPN (if not already active) 
else
 	netstat -lu | grep 49150 > /dev/null
 	if [ $? -eq 1 ]; then
		wg-quick up wg0-auber
	fi
fi
