config setup
        charondebug="ike 1, knl 1, cfg 1"
        uniqueids=no
        strictcrlpolicy=no
    
conn gwB-to-gwA
        auto=start        
        type=tunnel
        authby=pubkey
        
        # ---  GW-B (local) ---
        left=172.20.10.8
        leftid=<IP-public-GW-B>
        leftsubnet=172.20.10.0/28
    	  leftcert=gwB-cert.pem

        # --- GW-A (distant) ---
        right=<IP-public-GW-A> 
        rightid=<IP-public-GW-A>
        rightsubnet=192.168.1.0/24
    
        # --- IKEv2 + Cipher suites ---
        ike=aes256gcm16-sha384-ecp384!
    	  esp=aes256gcm16-sha384!
        keyexchange=ikev2
    
        # --- NAT-Traversal ---
        forceencaps=yes         
        fragmentation=yes
        
        # --- Policy ---
        dpddelay=30s
        dpdtimeout=120s
        dpdaction=restart
        keyingtries=%forever
