config setup
	charondebug="ike 1, knl 1, cfg 1"
	uniqueids=yes
    
conn gwA-to-gwB
	auto=start			
	type=tunnel
	
	# --- Authentification via certificates ---
	authby=pubkey
        
	# ---  GW-A (local) ---
	left=192.168.1.167       	
	leftid=gwA.vpn.local  	
	leftsubnet=192.168.1.0/24  	
	leftcert=gwA-cert.pem
        
	# --- GW-B (distant) ---
	right=<IP-public-GW-B>
	rightid=gwB.vpn.local
	rightsubnet=172.20.10.0/28 	
    
	# --- IKEv2 + Cipher suites ---
	ike=aes256gcm16-sha384-ecp384!
	esp=aes256gcm16-sha384!
	keyexchange=ikev2

	# --- Policy ---
	dpddelay=30s
	dpdtimeout=120s
	dpdaction=restart	
	keyingtries=%forever
