config setup
    	charondebug="ike 1, knl 1, cfg 1"
    	uniqueids=no  			
    	strictcrlpolicy=no
    
conn gwA-to-gwB
	    auto=start				
    	type=tunnel

      # --- Authentification via PKI (public key signatures) ---
      authby=pubkey
        
    	# ---  GW-A (local) ---
    	left=192.168.1.167       	
    	leftid=<IP-public-GW-A>      	
    	leftsubnet=192.168.1.0/24  	
 	    leftcert=gwA-cert.pem

    	# --- GW-B (distant) ---
    	right=%any               	
    	rightsubnet=172.20.10.0/28 	
    
    	# --- IKEv2 + Cipher suites ---
      ike=aes256gcm16-sha384-ecp384!
    	esp=aes256gcm16-sha384!
    
    	keyexchange=ikev2
    
    	# --- NAT-Traversal ---
    	forceencaps=yes         
      fragmentation=yes
        
    	# --- Policy ---
    	dpddelay=30s
    	dpdtimeout=120s
    	dpdaction=restart
	    keyingtries=%forever
