[Interface]
Address=10.9.4.100/24
PrivateKey=QK7A/vOMbonV4EDDezE9+e4itF9Q5tM7/j5e+lNmklM=
ListenPort=39501
PostUp=iptables -t nat -A POSTROUTING -s 10.9.4.0/24 -o wlp6s0 -j MASQUERADE
PostDown=iptables -t nat -D POSTROUTING -s 10.9.4.0/24 -o wlp6s0 -j MASQUERADE

[Peer]
PublicKey=d0wDiOvUGaq4nVVpsOroRLCGb0Bcbmfio86Zweu2R20=
Endpoint=82.X.Y.Z:49150
AllowedIPs=10.9.4.0/24, 192.168.0.0/16, 10.9.2.0/24
PersistentKeepalive=25
